name: flutter_template
description: starting template for a flutter project
version: 1.0.0+0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_template_api:
    path: ./generated/api
  formz: ^0.6.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  pigeon: ^17.0.0
  shared_preferences: ^2.1.0


dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
    - lib/app/features/
